In [1]:
import numpy as np

In [2]:
#Q4
array = np.ones((5, 5))
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [3]:
#Q5
array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([0, 40])
result = np.isin(array1, array2)
print(result)

[ True False False  True False]


In [4]:
#Q6
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70])
xor_result = np.setxor1d(array1, array2)
print(xor_result)

[ 0 20 30 50 60 70 80]


In [5]:
#Q7
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
stacked_array = np.column_stack((array1, array2))
print(stacked_array)

[[1 4]
 [2 5]
 [3 6]]


In [6]:
#Q8
matrix = np.array([[2, 3], [4, 5]])
rank = np.linalg.matrix_rank(matrix)
trace = np.trace(matrix)
determinant = np.linalg.det(matrix)

print(f"Rank: {rank}")
print(f"Trace: {trace}")
print(f"Determinant: {determinant}")

Rank: 2
Trace: 7
Determinant: -2.0
