In [1]:
import numpy as np
import scipy

In [2]:
#Q1
from scipy import io
array_ones = np.ones((4, 4))
np.savetxt('test.txt', array_ones)
loaded_array = np.loadtxt('test.txt')
print(loaded_array)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
#Q2
from scipy import special

cubic_roots = special.cbrt([27, 64, 891])
print(cubic_roots)

[3.         4.         9.62260299]


In [4]:
#Q3
from scipy import linalg
matrix = np.array([[4, 5], [3, 2]])
determinant = linalg.det(matrix)
inverse = linalg.inv(matrix)
print(f"Determinant: {determinant}")
print(f"Inverse: \n{inverse}")

Determinant: -7.0
Inverse: 
[[-0.28571429  0.71428571]
 [ 0.42857143 -0.57142857]]


In [5]:
#Q4
matrix = np.array([[5, 4], [6, 3]])
eigenvalues, eigenvectors = linalg.eig(matrix)
print(f"Eigenvalues: {eigenvalues}")
print(f"Eigenvectors: \n{eigenvectors}")

Eigenvalues: [ 9.+0.j -1.+0.j]
Eigenvectors: 
[[ 0.70710678 -0.5547002 ]
 [ 0.70710678  0.83205029]]


In [6]:
#q5
from scipy import sparse
A = sparse.csr_matrix([[1, 0, 0], [0, 2, 0], [0, 0, 3]])
B = sparse.csr_matrix([[0, 0, 4], [0, 5, 0], [6, 0, 0]])
print("Matrix A (in dense form):\n", A.toarray())
print("Matrix B (in dense form):\n", B.toarray())
C = A + B
print("Matrix A + Matrix B (dense form):\n", C.toarray())
D = A.dot(B)
print("Matrix A * Matrix B (dense form):\n", D.toarray())

Matrix A (in dense form):
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
Matrix B (in dense form):
 [[0 0 4]
 [0 5 0]
 [6 0 0]]
Matrix A + Matrix B (dense form):
 [[1 0 4]
 [0 7 0]
 [6 0 3]]
Matrix A * Matrix B (dense form):
 [[ 0  0  4]
 [ 0 10  0]
 [18  0  0]]
