In [1]:
import numpy as np

In [4]:
#A1
arr = np.random.randint(1, 21, size=(5,5))
print(arr)

[[14 12 10 14  7]
 [ 7 19 10 10  2]
 [ 8  2 18 16 16]
 [ 6 17 14 15 16]
 [ 4 16  6 18 11]]


In [5]:
arr[:,2] = 1
print(arr)

[[14 12  1 14  7]
 [ 7 19  1 10  2]
 [ 8  2  1 16 16]
 [ 6 17  1 15 16]
 [ 4 16  1 18 11]]


In [6]:
a1 = np.random.randint(1,17,size=(4,4))
print(a1)

[[ 7  3  6  6]
 [ 1 10  5 15]
 [ 3  3  8  7]
 [ 5  3 12  4]]


In [7]:
np.fill_diagonal(a1,0)
print(a1)

[[ 0  3  6  6]
 [ 1  0  5 15]
 [ 3  3  0  7]
 [ 5  3 12  0]]


In [8]:
#A2
a1 = np.arange(1,37).reshape(6,6)
print(a1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [9]:
a1[2:5,1:4]

array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [11]:
border_elements = np.concatenate((a1[0, :], a1[-1, :], a1[1:-1, 0], a1[1:-1, -1]))
print("Border elements:")
print(border_elements)

Border elements:
[ 1  2  3  4  5  6 31 32 33 34 35 36  7 13 19 25 12 18 24 30]
