In [2]:
import numpy as np
# Creattion of 1D and 2D arrays
a = np.array([1,2,3])

b = np.array([[1,2,3],[4,5,6]])

In [ ]:
a.ndim
# Get dimension of array
#Get Shape of array
a.shape  # return (row, col)

In [13]:
c =np.random.randint(1,10,(2,3))
# Initialize array with random int values
print(c)

[[8 8 5]
 [2 1 9]]


In [25]:
arr = np.array([[1,2,3,4]])
r1 = np.repeat(arr,3,axis=1)
#Initialize array with repeat values
print(r1)

[[1 1 1 2 2 2 3 3 3 4 4 4]]


In [30]:
a = np.array([[1,3,2],[0,5,4]])
np.min(a,axis=0)
# Get min value of array with a particular axis

array([0, 3, 2])